<?php
/**
 * SetCustomCoveragePayload
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* EBSCO HoldingsIQ
 *
* The EBSCO HoldingsIQ service retrieves vendor, package and title related information in JSON format.  The information includes customer selected resources as reflected in the EBSCO Knowledge Base for both EBSCO managed and customer managed resources.
 *
* OpenAPI spec version: 1.0.0
 * Contact: support@ebsco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SetCustomCoveragePayload Class Doc Comment
 *
 * @category Class
 * @description This object represents data elements to set custom coverage, coverage statement and custom embargo.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SetCustomCoveragePayload implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'setCustomCoveragePayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'is_selected' => 'bool',
'custom_coverage_list' => '\Swagger\Client\Model\CoverageDates[]',
'coverage_statement' => 'string',
'custom_embargo_period' => '\Swagger\Client\Model\EmbargoPeriod'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'is_selected' => null,
'custom_coverage_list' => null,
'coverage_statement' => null,
'custom_embargo_period' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'is_selected' => 'isSelected',
'custom_coverage_list' => 'customCoverageList',
'coverage_statement' => 'coverageStatement',
'custom_embargo_period' => 'customEmbargoPeriod'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'is_selected' => 'setIsSelected',
'custom_coverage_list' => 'setCustomCoverageList',
'coverage_statement' => 'setCoverageStatement',
'custom_embargo_period' => 'setCustomEmbargoPeriod'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'is_selected' => 'getIsSelected',
'custom_coverage_list' => 'getCustomCoverageList',
'coverage_statement' => 'getCoverageStatement',
'custom_embargo_period' => 'getCustomEmbargoPeriod'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['is_selected'] = isset($data['is_selected']) ? $data['is_selected'] : null;
        $this->container['custom_coverage_list'] = isset($data['custom_coverage_list']) ? $data['custom_coverage_list'] : null;
        $this->container['coverage_statement'] = isset($data['coverage_statement']) ? $data['coverage_statement'] : null;
        $this->container['custom_embargo_period'] = isset($data['custom_embargo_period']) ? $data['custom_embargo_period'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['is_selected'] === null) {
            $invalidProperties[] = "'is_selected' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['is_selected'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets is_selected
     *
     * @return bool
     */
    public function getIsSelected()
    {
        return $this->container['is_selected'];
    }

    /**
     * Sets is_selected
     *
     * @param bool $is_selected Indicates if selected in a customer's account.
     *
     * @return $this
     */
    public function setIsSelected($is_selected)
    {
        $this->container['is_selected'] = $is_selected;

        return $this;
    }

    /**
     * Gets custom_coverage_list
     *
     * @return \Swagger\Client\Model\CoverageDates[]
     */
    public function getCustomCoverageList()
    {
        return $this->container['custom_coverage_list'];
    }

    /**
     * Sets custom_coverage_list
     *
     * @param \Swagger\Client\Model\CoverageDates[] $custom_coverage_list Coverage List
     *
     * @return $this
     */
    public function setCustomCoverageList($custom_coverage_list)
    {
        $this->container['custom_coverage_list'] = $custom_coverage_list;

        return $this;
    }

    /**
     * Gets coverage_statement
     *
     * @return string
     */
    public function getCoverageStatement()
    {
        return $this->container['coverage_statement'];
    }

    /**
     * Sets coverage_statement
     *
     * @param string $coverage_statement Coverage Statement
     *
     * @return $this
     */
    public function setCoverageStatement($coverage_statement)
    {
        $this->container['coverage_statement'] = $coverage_statement;

        return $this;
    }

    /**
     * Gets custom_embargo_period
     *
     * @return \Swagger\Client\Model\EmbargoPeriod
     */
    public function getCustomEmbargoPeriod()
    {
        return $this->container['custom_embargo_period'];
    }

    /**
     * Sets custom_embargo_period
     *
     * @param \Swagger\Client\Model\EmbargoPeriod $custom_embargo_period custom_embargo_period
     *
     * @return $this
     */
    public function setCustomEmbargoPeriod($custom_embargo_period)
    {
        $this->container['custom_embargo_period'] = $custom_embargo_period;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
