<?php
/**
 * SetManagedPackagePayload
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* EBSCO HoldingsIQ
 *
* The EBSCO HoldingsIQ service retrieves vendor, package and title related information in JSON format.  The information includes customer selected resources as reflected in the EBSCO Knowledge Base for both EBSCO managed and customer managed resources.
 *
* OpenAPI spec version: 1.0.0
 * Contact: support@ebsco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SetManagedPackagePayload Class Doc Comment
 *
 * @category Class
 * @description This object represents data elements that describe the payload to update values for a managed package.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SetManagedPackagePayload implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'setManagedPackagePayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'is_selected' => 'bool',
'is_hidden' => 'bool',
'allow_ebsco_to_add_titles' => 'bool',
'custom_coverage' => '\Swagger\Client\Model\CoverageDates',
'proxy' => '\Swagger\Client\Model\ProxyInfo',
'package_token' => '\Swagger\Client\Model\TokenDetails'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'is_selected' => null,
'is_hidden' => null,
'allow_ebsco_to_add_titles' => null,
'custom_coverage' => null,
'proxy' => null,
'package_token' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'is_selected' => 'isSelected',
'is_hidden' => 'isHidden',
'allow_ebsco_to_add_titles' => 'allowEbscoToAddTitles',
'custom_coverage' => 'customCoverage',
'proxy' => 'proxy',
'package_token' => 'packageToken'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'is_selected' => 'setIsSelected',
'is_hidden' => 'setIsHidden',
'allow_ebsco_to_add_titles' => 'setAllowEbscoToAddTitles',
'custom_coverage' => 'setCustomCoverage',
'proxy' => 'setProxy',
'package_token' => 'setPackageToken'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'is_selected' => 'getIsSelected',
'is_hidden' => 'getIsHidden',
'allow_ebsco_to_add_titles' => 'getAllowEbscoToAddTitles',
'custom_coverage' => 'getCustomCoverage',
'proxy' => 'getProxy',
'package_token' => 'getPackageToken'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['is_selected'] = isset($data['is_selected']) ? $data['is_selected'] : null;
        $this->container['is_hidden'] = isset($data['is_hidden']) ? $data['is_hidden'] : null;
        $this->container['allow_ebsco_to_add_titles'] = isset($data['allow_ebsco_to_add_titles']) ? $data['allow_ebsco_to_add_titles'] : null;
        $this->container['custom_coverage'] = isset($data['custom_coverage']) ? $data['custom_coverage'] : null;
        $this->container['proxy'] = isset($data['proxy']) ? $data['proxy'] : null;
        $this->container['package_token'] = isset($data['package_token']) ? $data['package_token'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['is_selected'] === null) {
            $invalidProperties[] = "'is_selected' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['is_selected'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets is_selected
     *
     * @return bool
     */
    public function getIsSelected()
    {
        return $this->container['is_selected'];
    }

    /**
     * Sets is_selected
     *
     * @param bool $is_selected Indicates if the packages is selected in a customer's account.
     *
     * @return $this
     */
    public function setIsSelected($is_selected)
    {
        $this->container['is_selected'] = $is_selected;

        return $this;
    }

    /**
     * Gets is_hidden
     *
     * @return bool
     */
    public function getIsHidden()
    {
        return $this->container['is_hidden'];
    }

    /**
     * Sets is_hidden
     *
     * @param bool $is_hidden Field to indicate if title is hidden.
     *
     * @return $this
     */
    public function setIsHidden($is_hidden)
    {
        $this->container['is_hidden'] = $is_hidden;

        return $this;
    }

    /**
     * Gets allow_ebsco_to_add_titles
     *
     * @return bool
     */
    public function getAllowEbscoToAddTitles()
    {
        return $this->container['allow_ebsco_to_add_titles'];
    }

    /**
     * Sets allow_ebsco_to_add_titles
     *
     * @param bool $allow_ebsco_to_add_titles Indicates if EBSCO is allowed to add titles.  If the package type is custom, then allowEbscoToAddTitles will always be set to false.
     *
     * @return $this
     */
    public function setAllowEbscoToAddTitles($allow_ebsco_to_add_titles)
    {
        $this->container['allow_ebsco_to_add_titles'] = $allow_ebsco_to_add_titles;

        return $this;
    }

    /**
     * Gets custom_coverage
     *
     * @return \Swagger\Client\Model\CoverageDates
     */
    public function getCustomCoverage()
    {
        return $this->container['custom_coverage'];
    }

    /**
     * Sets custom_coverage
     *
     * @param \Swagger\Client\Model\CoverageDates $custom_coverage custom_coverage
     *
     * @return $this
     */
    public function setCustomCoverage($custom_coverage)
    {
        $this->container['custom_coverage'] = $custom_coverage;

        return $this;
    }

    /**
     * Gets proxy
     *
     * @return \Swagger\Client\Model\ProxyInfo
     */
    public function getProxy()
    {
        return $this->container['proxy'];
    }

    /**
     * Sets proxy
     *
     * @param \Swagger\Client\Model\ProxyInfo $proxy proxy
     *
     * @return $this
     */
    public function setProxy($proxy)
    {
        $this->container['proxy'] = $proxy;

        return $this;
    }

    /**
     * Gets package_token
     *
     * @return \Swagger\Client\Model\TokenDetails
     */
    public function getPackageToken()
    {
        return $this->container['package_token'];
    }

    /**
     * Sets package_token
     *
     * @param \Swagger\Client\Model\TokenDetails $package_token package_token
     *
     * @return $this
     */
    public function setPackageToken($package_token)
    {
        $this->container['package_token'] = $package_token;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
