<?php
/**
 * SetUserDefinedFieldsPayload
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* EBSCO HoldingsIQ
 *
* The EBSCO HoldingsIQ service retrieves vendor, package and title related information in JSON format.  The information includes customer selected resources as reflected in the EBSCO Knowledge Base for both EBSCO managed and customer managed resources.
 *
* OpenAPI spec version: 1.0.0
 * Contact: support@ebsco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SetUserDefinedFieldsPayload Class Doc Comment
 *
 * @category Class
 * @description This object represents data elements to set user defined fields.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SetUserDefinedFieldsPayload implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'setUserDefinedFieldsPayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'is_selected' => 'bool',
'user_defined_field1' => 'string',
'user_defined_field2' => 'string',
'user_defined_field3' => 'string',
'user_defined_field4' => 'string',
'user_defined_field5' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'is_selected' => null,
'user_defined_field1' => null,
'user_defined_field2' => null,
'user_defined_field3' => null,
'user_defined_field4' => null,
'user_defined_field5' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'is_selected' => 'isSelected',
'user_defined_field1' => 'userDefinedField1',
'user_defined_field2' => 'userDefinedField2',
'user_defined_field3' => 'userDefinedField3',
'user_defined_field4' => 'userDefinedField4',
'user_defined_field5' => 'userDefinedField5'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'is_selected' => 'setIsSelected',
'user_defined_field1' => 'setUserDefinedField1',
'user_defined_field2' => 'setUserDefinedField2',
'user_defined_field3' => 'setUserDefinedField3',
'user_defined_field4' => 'setUserDefinedField4',
'user_defined_field5' => 'setUserDefinedField5'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'is_selected' => 'getIsSelected',
'user_defined_field1' => 'getUserDefinedField1',
'user_defined_field2' => 'getUserDefinedField2',
'user_defined_field3' => 'getUserDefinedField3',
'user_defined_field4' => 'getUserDefinedField4',
'user_defined_field5' => 'getUserDefinedField5'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['is_selected'] = isset($data['is_selected']) ? $data['is_selected'] : null;
        $this->container['user_defined_field1'] = isset($data['user_defined_field1']) ? $data['user_defined_field1'] : null;
        $this->container['user_defined_field2'] = isset($data['user_defined_field2']) ? $data['user_defined_field2'] : null;
        $this->container['user_defined_field3'] = isset($data['user_defined_field3']) ? $data['user_defined_field3'] : null;
        $this->container['user_defined_field4'] = isset($data['user_defined_field4']) ? $data['user_defined_field4'] : null;
        $this->container['user_defined_field5'] = isset($data['user_defined_field5']) ? $data['user_defined_field5'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['is_selected'] === null) {
            $invalidProperties[] = "'is_selected' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['is_selected'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets is_selected
     *
     * @return bool
     */
    public function getIsSelected()
    {
        return $this->container['is_selected'];
    }

    /**
     * Sets is_selected
     *
     * @param bool $is_selected Indicates if selected in a customer's account.
     *
     * @return $this
     */
    public function setIsSelected($is_selected)
    {
        $this->container['is_selected'] = $is_selected;

        return $this;
    }

    /**
     * Gets user_defined_field1
     *
     * @return string
     */
    public function getUserDefinedField1()
    {
        return $this->container['user_defined_field1'];
    }

    /**
     * Sets user_defined_field1
     *
     * @param string $user_defined_field1 User Defined Field 1
     *
     * @return $this
     */
    public function setUserDefinedField1($user_defined_field1)
    {
        $this->container['user_defined_field1'] = $user_defined_field1;

        return $this;
    }

    /**
     * Gets user_defined_field2
     *
     * @return string
     */
    public function getUserDefinedField2()
    {
        return $this->container['user_defined_field2'];
    }

    /**
     * Sets user_defined_field2
     *
     * @param string $user_defined_field2 User Defined Field 2
     *
     * @return $this
     */
    public function setUserDefinedField2($user_defined_field2)
    {
        $this->container['user_defined_field2'] = $user_defined_field2;

        return $this;
    }

    /**
     * Gets user_defined_field3
     *
     * @return string
     */
    public function getUserDefinedField3()
    {
        return $this->container['user_defined_field3'];
    }

    /**
     * Sets user_defined_field3
     *
     * @param string $user_defined_field3 User Defined Field 3
     *
     * @return $this
     */
    public function setUserDefinedField3($user_defined_field3)
    {
        $this->container['user_defined_field3'] = $user_defined_field3;

        return $this;
    }

    /**
     * Gets user_defined_field4
     *
     * @return string
     */
    public function getUserDefinedField4()
    {
        return $this->container['user_defined_field4'];
    }

    /**
     * Sets user_defined_field4
     *
     * @param string $user_defined_field4 User Defined Field 4
     *
     * @return $this
     */
    public function setUserDefinedField4($user_defined_field4)
    {
        $this->container['user_defined_field4'] = $user_defined_field4;

        return $this;
    }

    /**
     * Gets user_defined_field5
     *
     * @return string
     */
    public function getUserDefinedField5()
    {
        return $this->container['user_defined_field5'];
    }

    /**
     * Sets user_defined_field5
     *
     * @param string $user_defined_field5 User Defined Field 5
     *
     * @return $this
     */
    public function setUserDefinedField5($user_defined_field5)
    {
        $this->container['user_defined_field5'] = $user_defined_field5;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
