<?php
/**
 * TitleManaged
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* EBSCO HoldingsIQ
 *
* The EBSCO HoldingsIQ service retrieves vendor, package and title related information in JSON format.  The information includes customer selected resources as reflected in the EBSCO Knowledge Base for both EBSCO managed and customer managed resources.
 *
* OpenAPI spec version: 1.0.0
 * Contact: support@ebsco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * TitleManaged Class Doc Comment
 *
 * @category Class
 * @description This object represents data elements that describe a title.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TitleManaged implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'titleManaged';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'description' => 'string',
'edition' => 'string',
'is_peer_reviewed' => 'bool',
'contributors_list' => '\Swagger\Client\Model\ContributorID[]',
'title_id' => 'int',
'title_name' => 'string',
'publisher_name' => 'string',
'identifiers_list' => '\Swagger\Client\Model\Identifier[]',
'subjects_list' => '\Swagger\Client\Model\NItem[]',
'is_title_custom' => 'bool',
'pub_type' => 'string',
'customer_resources_list' => '\Swagger\Client\Model\CustomerResources[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'description' => null,
'edition' => null,
'is_peer_reviewed' => null,
'contributors_list' => null,
'title_id' => null,
'title_name' => null,
'publisher_name' => null,
'identifiers_list' => null,
'subjects_list' => null,
'is_title_custom' => null,
'pub_type' => null,
'customer_resources_list' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'description' => 'description',
'edition' => 'edition',
'is_peer_reviewed' => 'isPeerReviewed',
'contributors_list' => 'contributorsList',
'title_id' => 'titleId',
'title_name' => 'titleName',
'publisher_name' => 'publisherName',
'identifiers_list' => 'identifiersList',
'subjects_list' => 'subjectsList',
'is_title_custom' => 'isTitleCustom',
'pub_type' => 'pubType',
'customer_resources_list' => 'customerResourcesList'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'description' => 'setDescription',
'edition' => 'setEdition',
'is_peer_reviewed' => 'setIsPeerReviewed',
'contributors_list' => 'setContributorsList',
'title_id' => 'setTitleId',
'title_name' => 'setTitleName',
'publisher_name' => 'setPublisherName',
'identifiers_list' => 'setIdentifiersList',
'subjects_list' => 'setSubjectsList',
'is_title_custom' => 'setIsTitleCustom',
'pub_type' => 'setPubType',
'customer_resources_list' => 'setCustomerResourcesList'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'description' => 'getDescription',
'edition' => 'getEdition',
'is_peer_reviewed' => 'getIsPeerReviewed',
'contributors_list' => 'getContributorsList',
'title_id' => 'getTitleId',
'title_name' => 'getTitleName',
'publisher_name' => 'getPublisherName',
'identifiers_list' => 'getIdentifiersList',
'subjects_list' => 'getSubjectsList',
'is_title_custom' => 'getIsTitleCustom',
'pub_type' => 'getPubType',
'customer_resources_list' => 'getCustomerResourcesList'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['edition'] = isset($data['edition']) ? $data['edition'] : null;
        $this->container['is_peer_reviewed'] = isset($data['is_peer_reviewed']) ? $data['is_peer_reviewed'] : null;
        $this->container['contributors_list'] = isset($data['contributors_list']) ? $data['contributors_list'] : null;
        $this->container['title_id'] = isset($data['title_id']) ? $data['title_id'] : null;
        $this->container['title_name'] = isset($data['title_name']) ? $data['title_name'] : null;
        $this->container['publisher_name'] = isset($data['publisher_name']) ? $data['publisher_name'] : null;
        $this->container['identifiers_list'] = isset($data['identifiers_list']) ? $data['identifiers_list'] : null;
        $this->container['subjects_list'] = isset($data['subjects_list']) ? $data['subjects_list'] : null;
        $this->container['is_title_custom'] = isset($data['is_title_custom']) ? $data['is_title_custom'] : null;
        $this->container['pub_type'] = isset($data['pub_type']) ? $data['pub_type'] : null;
        $this->container['customer_resources_list'] = isset($data['customer_resources_list']) ? $data['customer_resources_list'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['title_id'] === null) {
            $invalidProperties[] = "'title_id' can't be null";
        }
        if ($this->container['title_name'] === null) {
            $invalidProperties[] = "'title_name' can't be null";
        }
        if ($this->container['pub_type'] === null) {
            $invalidProperties[] = "'pub_type' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['title_id'] === null) {
            return false;
        }
        if ($this->container['title_name'] === null) {
            return false;
        }
        if ($this->container['pub_type'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description Title Description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets edition
     *
     * @return string
     */
    public function getEdition()
    {
        return $this->container['edition'];
    }

    /**
     * Sets edition
     *
     * @param string $edition Title Edition
     *
     * @return $this
     */
    public function setEdition($edition)
    {
        $this->container['edition'] = $edition;

        return $this;
    }

    /**
     * Gets is_peer_reviewed
     *
     * @return bool
     */
    public function getIsPeerReviewed()
    {
        return $this->container['is_peer_reviewed'];
    }

    /**
     * Sets is_peer_reviewed
     *
     * @param bool $is_peer_reviewed Is this title peer reviewed.
     *
     * @return $this
     */
    public function setIsPeerReviewed($is_peer_reviewed)
    {
        $this->container['is_peer_reviewed'] = $is_peer_reviewed;

        return $this;
    }

    /**
     * Gets contributors_list
     *
     * @return \Swagger\Client\Model\ContributorID[]
     */
    public function getContributorsList()
    {
        return $this->container['contributors_list'];
    }

    /**
     * Sets contributors_list
     *
     * @param \Swagger\Client\Model\ContributorID[] $contributors_list Contributor ID List
     *
     * @return $this
     */
    public function setContributorsList($contributors_list)
    {
        $this->container['contributors_list'] = $contributors_list;

        return $this;
    }

    /**
     * Gets title_id
     *
     * @return int
     */
    public function getTitleId()
    {
        return $this->container['title_id'];
    }

    /**
     * Sets title_id
     *
     * @param int $title_id Title ID
     *
     * @return $this
     */
    public function setTitleId($title_id)
    {
        $this->container['title_id'] = $title_id;

        return $this;
    }

    /**
     * Gets title_name
     *
     * @return string
     */
    public function getTitleName()
    {
        return $this->container['title_name'];
    }

    /**
     * Sets title_name
     *
     * @param string $title_name Title Name
     *
     * @return $this
     */
    public function setTitleName($title_name)
    {
        $this->container['title_name'] = $title_name;

        return $this;
    }

    /**
     * Gets publisher_name
     *
     * @return string
     */
    public function getPublisherName()
    {
        return $this->container['publisher_name'];
    }

    /**
     * Sets publisher_name
     *
     * @param string $publisher_name Publisher Name
     *
     * @return $this
     */
    public function setPublisherName($publisher_name)
    {
        $this->container['publisher_name'] = $publisher_name;

        return $this;
    }

    /**
     * Gets identifiers_list
     *
     * @return \Swagger\Client\Model\Identifier[]
     */
    public function getIdentifiersList()
    {
        return $this->container['identifiers_list'];
    }

    /**
     * Sets identifiers_list
     *
     * @param \Swagger\Client\Model\Identifier[] $identifiers_list Identifiers
     *
     * @return $this
     */
    public function setIdentifiersList($identifiers_list)
    {
        $this->container['identifiers_list'] = $identifiers_list;

        return $this;
    }

    /**
     * Gets subjects_list
     *
     * @return \Swagger\Client\Model\NItem[]
     */
    public function getSubjectsList()
    {
        return $this->container['subjects_list'];
    }

    /**
     * Sets subjects_list
     *
     * @param \Swagger\Client\Model\NItem[] $subjects_list Subjects
     *
     * @return $this
     */
    public function setSubjectsList($subjects_list)
    {
        $this->container['subjects_list'] = $subjects_list;

        return $this;
    }

    /**
     * Gets is_title_custom
     *
     * @return bool
     */
    public function getIsTitleCustom()
    {
        return $this->container['is_title_custom'];
    }

    /**
     * Sets is_title_custom
     *
     * @param bool $is_title_custom Is this a custom title owned by the customer.
     *
     * @return $this
     */
    public function setIsTitleCustom($is_title_custom)
    {
        $this->container['is_title_custom'] = $is_title_custom;

        return $this;
    }

    /**
     * Gets pub_type
     *
     * @return string
     */
    public function getPubType()
    {
        return $this->container['pub_type'];
    }

    /**
     * Sets pub_type
     *
     * @param string $pub_type Publication Type
     *
     * @return $this
     */
    public function setPubType($pub_type)
    {
        $this->container['pub_type'] = $pub_type;

        return $this;
    }

    /**
     * Gets customer_resources_list
     *
     * @return \Swagger\Client\Model\CustomerResources[]
     */
    public function getCustomerResourcesList()
    {
        return $this->container['customer_resources_list'];
    }

    /**
     * Sets customer_resources_list
     *
     * @param \Swagger\Client\Model\CustomerResources[] $customer_resources_list Customer Resources List
     *
     * @return $this
     */
    public function setCustomerResourcesList($customer_resources_list)
    {
        $this->container['customer_resources_list'] = $customer_resources_list;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
