<?php
/**
 * CustomTitlePayloadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* EBSCO HoldingsIQ
 *
* The EBSCO HoldingsIQ service retrieves vendor, package and title related information in JSON format.  The information includes customer selected resources as reflected in the EBSCO Knowledge Base for both EBSCO managed and customer managed resources.
 *
* OpenAPI spec version: 1.0.0
 * Contact: support@ebsco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomTitlePayloadTest Class Doc Comment
 *
 * @category    Class
 * @description Custom Title Payload
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomTitlePayloadTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomTitlePayload"
     */
    public function testCustomTitlePayload()
    {
    }

    /**
     * Test attribute "title_name"
     */
    public function testPropertyTitleName()
    {
    }

    /**
     * Test attribute "pub_type"
     */
    public function testPropertyPubType()
    {
    }

    /**
     * Test attribute "publisher_name"
     */
    public function testPropertyPublisherName()
    {
    }

    /**
     * Test attribute "is_peer_reviewed"
     */
    public function testPropertyIsPeerReviewed()
    {
    }

    /**
     * Test attribute "edition"
     */
    public function testPropertyEdition()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "identifiers_list"
     */
    public function testPropertyIdentifiersList()
    {
    }

    /**
     * Test attribute "contributors_list"
     */
    public function testPropertyContributorsList()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "custom_coverage_list"
     */
    public function testPropertyCustomCoverageList()
    {
    }

    /**
     * Test attribute "coverage_statement"
     */
    public function testPropertyCoverageStatement()
    {
    }

    /**
     * Test attribute "custom_embargo_period"
     */
    public function testPropertyCustomEmbargoPeriod()
    {
    }

    /**
     * Test attribute "user_defined_field1"
     */
    public function testPropertyUserDefinedField1()
    {
    }

    /**
     * Test attribute "user_defined_field2"
     */
    public function testPropertyUserDefinedField2()
    {
    }

    /**
     * Test attribute "user_defined_field3"
     */
    public function testPropertyUserDefinedField3()
    {
    }

    /**
     * Test attribute "user_defined_field4"
     */
    public function testPropertyUserDefinedField4()
    {
    }

    /**
     * Test attribute "user_defined_field5"
     */
    public function testPropertyUserDefinedField5()
    {
    }
}
