<?php
/**
 * CustomerResourcesPackageIdTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* EBSCO HoldingsIQ
 *
* The EBSCO HoldingsIQ service retrieves vendor, package and title related information in JSON format.  The information includes customer selected resources as reflected in the EBSCO Knowledge Base for both EBSCO managed and customer managed resources.
 *
* OpenAPI spec version: 1.0.0
 * Contact: support@ebsco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomerResourcesPackageIdTest Class Doc Comment
 *
 * @category    Class
 * @description This object represents data elements that describe customer resources information.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerResourcesPackageIdTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerResourcesPackageId"
     */
    public function testCustomerResourcesPackageId()
    {
    }

    /**
     * Test attribute "title_id"
     */
    public function testPropertyTitleId()
    {
    }

    /**
     * Test attribute "package_id"
     */
    public function testPropertyPackageId()
    {
    }

    /**
     * Test attribute "package_name"
     */
    public function testPropertyPackageName()
    {
    }

    /**
     * Test attribute "package_type"
     */
    public function testPropertyPackageType()
    {
    }

    /**
     * Test attribute "vendor_id"
     */
    public function testPropertyVendorId()
    {
    }

    /**
     * Test attribute "vendor_name"
     */
    public function testPropertyVendorName()
    {
    }

    /**
     * Test attribute "is_package_custom"
     */
    public function testPropertyIsPackageCustom()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "is_token_needed"
     */
    public function testPropertyIsTokenNeeded()
    {
    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "managed_coverage_list"
     */
    public function testPropertyManagedCoverageList()
    {
    }

    /**
     * Test attribute "custom_coverage_list"
     */
    public function testPropertyCustomCoverageList()
    {
    }

    /**
     * Test attribute "coverage_statement"
     */
    public function testPropertyCoverageStatement()
    {
    }

    /**
     * Test attribute "custom_embargo_period"
     */
    public function testPropertyCustomEmbargoPeriod()
    {
    }

    /**
     * Test attribute "managed_embargo_period"
     */
    public function testPropertyManagedEmbargoPeriod()
    {
    }

    /**
     * Test attribute "is_selected"
     */
    public function testPropertyIsSelected()
    {
    }

    /**
     * Test attribute "visibility_data"
     */
    public function testPropertyVisibilityData()
    {
    }

    /**
     * Test attribute "user_defined_field1"
     */
    public function testPropertyUserDefinedField1()
    {
    }

    /**
     * Test attribute "user_defined_field2"
     */
    public function testPropertyUserDefinedField2()
    {
    }

    /**
     * Test attribute "user_defined_field3"
     */
    public function testPropertyUserDefinedField3()
    {
    }

    /**
     * Test attribute "user_defined_field4"
     */
    public function testPropertyUserDefinedField4()
    {
    }

    /**
     * Test attribute "user_defined_field5"
     */
    public function testPropertyUserDefinedField5()
    {
    }
}
