<?php
/**
 * PackageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* EBSCO HoldingsIQ
 *
* The EBSCO HoldingsIQ service retrieves vendor, package and title related information in JSON format.  The information includes customer selected resources as reflected in the EBSCO Knowledge Base for both EBSCO managed and customer managed resources.
 *
* OpenAPI spec version: 1.0.0
 * Contact: support@ebsco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PackageTest Class Doc Comment
 *
 * @category    Class
 * @description This object represents data elements that describe a vendor package.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PackageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Package"
     */
    public function testPackage()
    {
    }

    /**
     * Test attribute "package_id"
     */
    public function testPropertyPackageId()
    {
    }

    /**
     * Test attribute "package_name"
     */
    public function testPropertyPackageName()
    {
    }

    /**
     * Test attribute "is_custom"
     */
    public function testPropertyIsCustom()
    {
    }

    /**
     * Test attribute "vendor_id"
     */
    public function testPropertyVendorId()
    {
    }

    /**
     * Test attribute "vendor_name"
     */
    public function testPropertyVendorName()
    {
    }

    /**
     * Test attribute "title_count"
     */
    public function testPropertyTitleCount()
    {
    }

    /**
     * Test attribute "is_selected"
     */
    public function testPropertyIsSelected()
    {
    }

    /**
     * Test attribute "visibility_data"
     */
    public function testPropertyVisibilityData()
    {
    }

    /**
     * Test attribute "selected_count"
     */
    public function testPropertySelectedCount()
    {
    }

    /**
     * Test attribute "is_token_needed"
     */
    public function testPropertyIsTokenNeeded()
    {
    }

    /**
     * Test attribute "custom_coverage"
     */
    public function testPropertyCustomCoverage()
    {
    }

    /**
     * Test attribute "content_type"
     */
    public function testPropertyContentType()
    {
    }

    /**
     * Test attribute "package_type"
     */
    public function testPropertyPackageType()
    {
    }
}
