<?php
/**
 * SetCustomPackagePayloadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* EBSCO HoldingsIQ
 *
* The EBSCO HoldingsIQ service retrieves vendor, package and title related information in JSON format.  The information includes customer selected resources as reflected in the EBSCO Knowledge Base for both EBSCO managed and customer managed resources.
 *
* OpenAPI spec version: 1.0.0
 * Contact: support@ebsco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SetCustomPackagePayloadTest Class Doc Comment
 *
 * @category    Class
 * @description This object represents data elements that describe the payload to update values for a custom package.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SetCustomPackagePayloadTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SetCustomPackagePayload"
     */
    public function testSetCustomPackagePayload()
    {
    }

    /**
     * Test attribute "package_name"
     */
    public function testPropertyPackageName()
    {
    }

    /**
     * Test attribute "content_type"
     */
    public function testPropertyContentType()
    {
    }

    /**
     * Test attribute "is_selected"
     */
    public function testPropertyIsSelected()
    {
    }

    /**
     * Test attribute "is_hidden"
     */
    public function testPropertyIsHidden()
    {
    }

    /**
     * Test attribute "custom_coverage"
     */
    public function testPropertyCustomCoverage()
    {
    }

    /**
     * Test attribute "proxy"
     */
    public function testPropertyProxy()
    {
    }
}
