<?php
/**
 * TitleCustomTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* EBSCO HoldingsIQ
 *
* The EBSCO HoldingsIQ service retrieves vendor, package and title related information in JSON format.  The information includes customer selected resources as reflected in the EBSCO Knowledge Base for both EBSCO managed and customer managed resources.
 *
* OpenAPI spec version: 1.0.0
 * Contact: support@ebsco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TitleCustomTest Class Doc Comment
 *
 * @category    Class
 * @description This object represents data elements that describe a custom title.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TitleCustomTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TitleCustom"
     */
    public function testTitleCustom()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "edition"
     */
    public function testPropertyEdition()
    {
    }

    /**
     * Test attribute "is_peer_reviewed"
     */
    public function testPropertyIsPeerReviewed()
    {
    }

    /**
     * Test attribute "contributors_list"
     */
    public function testPropertyContributorsList()
    {
    }

    /**
     * Test attribute "title_id"
     */
    public function testPropertyTitleId()
    {
    }

    /**
     * Test attribute "title_name"
     */
    public function testPropertyTitleName()
    {
    }

    /**
     * Test attribute "publisher_name"
     */
    public function testPropertyPublisherName()
    {
    }

    /**
     * Test attribute "identifiers_list"
     */
    public function testPropertyIdentifiersList()
    {
    }

    /**
     * Test attribute "subjects_list"
     */
    public function testPropertySubjectsList()
    {
    }

    /**
     * Test attribute "is_title_custom"
     */
    public function testPropertyIsTitleCustom()
    {
    }

    /**
     * Test attribute "pub_type"
     */
    public function testPropertyPubType()
    {
    }

    /**
     * Test attribute "customer_resources_list"
     */
    public function testPropertyCustomerResourcesList()
    {
    }
}
