<?php
/**
 * TitlesCombinedPayloadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* EBSCO HoldingsIQ
 *
* The EBSCO HoldingsIQ service retrieves vendor, package and title related information in JSON format.  The information includes customer selected resources as reflected in the EBSCO Knowledge Base for both EBSCO managed and customer managed resources.
 *
* OpenAPI spec version: 1.0.0
 * Contact: support@ebsco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TitlesCombinedPayloadTest Class Doc Comment
 *
 * @category    Class
 * @description This object represents data elements to set custom coverage, coverage statement and custom embargo.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TitlesCombinedPayloadTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TitlesCombinedPayload"
     */
    public function testTitlesCombinedPayload()
    {
    }

    /**
     * Test attribute "is_selected"
     */
    public function testPropertyIsSelected()
    {
    }

    /**
     * Test attribute "is_hidden"
     */
    public function testPropertyIsHidden()
    {
    }

    /**
     * Test attribute "user_defined_field1"
     */
    public function testPropertyUserDefinedField1()
    {
    }

    /**
     * Test attribute "user_defined_field2"
     */
    public function testPropertyUserDefinedField2()
    {
    }

    /**
     * Test attribute "user_defined_field3"
     */
    public function testPropertyUserDefinedField3()
    {
    }

    /**
     * Test attribute "user_defined_field4"
     */
    public function testPropertyUserDefinedField4()
    {
    }

    /**
     * Test attribute "user_defined_field5"
     */
    public function testPropertyUserDefinedField5()
    {
    }

    /**
     * Test attribute "custom_coverage_list"
     */
    public function testPropertyCustomCoverageList()
    {
    }

    /**
     * Test attribute "coverage_statement"
     */
    public function testPropertyCoverageStatement()
    {
    }

    /**
     * Test attribute "custom_embargo_period"
     */
    public function testPropertyCustomEmbargoPeriod()
    {
    }
}
