<?php
/**
 * VendorDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* EBSCO HoldingsIQ
 *
* The EBSCO HoldingsIQ service retrieves vendor, package and title related information in JSON format.  The information includes customer selected resources as reflected in the EBSCO Knowledge Base for both EBSCO managed and customer managed resources.
 *
* OpenAPI spec version: 1.0.0
 * Contact: support@ebsco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VendorDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description This object represents data elements that describe a vendor.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VendorDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VendorDetails"
     */
    public function testVendorDetails()
    {
    }

    /**
     * Test attribute "vendor_id"
     */
    public function testPropertyVendorId()
    {
    }

    /**
     * Test attribute "vendor_name"
     */
    public function testPropertyVendorName()
    {
    }

    /**
     * Test attribute "packages_total"
     */
    public function testPropertyPackagesTotal()
    {
    }

    /**
     * Test attribute "packages_selected"
     */
    public function testPropertyPackagesSelected()
    {
    }

    /**
     * Test attribute "is_customer"
     */
    public function testPropertyIsCustomer()
    {
    }

    /**
     * Test attribute "proxy"
     */
    public function testPropertyProxy()
    {
    }

    /**
     * Test attribute "vendor_token"
     */
    public function testPropertyVendorToken()
    {
    }
}
